package com.cmpt276.group3.grouproject.services;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.cmpt276.group3.grouproject.algorithms.GroupMatchingAlgorithm;
import com.cmpt276.group3.grouproject.enums.*;
import com.cmpt276.group3.grouproject.models.FriendGroup;
import com.cmpt276.group3.grouproject.models.FriendGroupRepository;
import com.cmpt276.group3.grouproject.models.GroupChatMessageRepository;
import com.cmpt276.group3.grouproject.models.GroupMembership;
import com.cmpt276.group3.grouproject.models.GroupMembershipRepository;
import com.cmpt276.group3.grouproject.models.GroupPreference;
import com.cmpt276.group3.grouproject.models.GroupPreferenceRepository;
import com.cmpt276.group3.grouproject.models.User;

// All group business rules live here so the controller stays thin and the rules stay testable.
// Throws IllegalArgumentException for bad input and IllegalStateException for rule violations,
// matching how UserService and ChatMessageService already behave.
@Service
public class FriendGroupService {

    private final FriendGroupRepository friendGroupRepository;
    private final GroupMembershipRepository groupMembershipRepository;
    private final GroupPreferenceRepository groupPreferenceRepository;
    private final GroupChatMessageRepository groupChatMessageRepository;

    public FriendGroupService(
            FriendGroupRepository friendGroupRepository,
            GroupMembershipRepository groupMembershipRepository,
            GroupPreferenceRepository groupPreferenceRepository,
            GroupChatMessageRepository groupChatMessageRepository
        ) {
        this.friendGroupRepository = friendGroupRepository;
        this.groupMembershipRepository = groupMembershipRepository;
        this.groupPreferenceRepository = groupPreferenceRepository;
        this.groupChatMessageRepository = groupChatMessageRepository;
    }

    // ----- Preferences (the group finder questionnaire) -----

    @Transactional(readOnly = true)
    public GroupPreference getPreference(User user) {
        if (user == null) {
            return null;
        }
        return groupPreferenceRepository.findByUser(user).orElse(null);
    }

    // Creates the user's preference row on first save, updates it after that.
    @Transactional
    public GroupPreference savePreference(User user, GroupPreference submitted) {
        if (user == null) {
            throw new IllegalArgumentException("User is required");
        }

        if (submitted == null) {
            throw new IllegalArgumentException("Preferences are required");
        }

        GroupPreference existing = groupPreferenceRepository.findByUser(user).orElse(null);

        if (existing == null) {
            existing = new GroupPreference(user);
        }

        existing.setUser(user);
        existing.setLookingForGroup(submitted.isLookingForGroup());
        existing.setVibe(submitted.getVibe());
        existing.setSize_preference(submitted.getSize_preference());
        existing.setMeetup_style(submitted.getMeetup_style());
        existing.setCampus(submitted.getCampus());
        existing.setAvailability(submitted.getAvailability());
        existing.setLifestyle(submitted.getLifestyle());
        existing.setTop_interest(submitted.getTop_interest());
        existing.setHobby1(submitted.getHobby1());
        existing.setHobby2(submitted.getHobby2());
        existing.setHobby3(submitted.getHobby3());
        existing.setBlurb(trimToLength(submitted.getBlurb(), 300));

        return groupPreferenceRepository.save(existing);
    }

    // ----- Group CRUD -----

    @Transactional(readOnly = true)
    public FriendGroup findGroup(Long groupId) {
        if (groupId == null) {
            return null;
        }
        return friendGroupRepository.findById(groupId).orElse(null);
    }

    // Creates a group and makes the creator its first ADMIN in the same transaction,
    // so a group can never exist without someone able to manage it.
    @Transactional
    public FriendGroup createGroup(User creator, FriendGroup form) {
        if (creator == null) {
            throw new IllegalArgumentException("A creator is required");
        }

        if (form == null || form.getName() == null || form.getName().isBlank()) {
            throw new IllegalArgumentException("A group name is required");
        }

        form.setId(null);
        form.setName(trimToLength(form.getName(), 60));
        form.setDescription(trimToLength(form.getDescription(), 500));
        form.setCreatedBy(creator);
        form.setAutoGenerated(false);

        GroupSizePreference size = form.getSize_preference();
        form.setMaxMembers(size == null ? 6 : size.getMaxSize());

        FriendGroup saved = friendGroupRepository.save(form);
        groupMembershipRepository.save(new GroupMembership(saved, creator, GroupRole.ADMIN));

        return saved;
    }

    // Only a group admin can change the group's details.
    @Transactional
    public FriendGroup updateGroup(User actor, Long groupId, String name, String description,
            boolean openToNewMembers) {
        FriendGroup group = requireGroup(groupId);
        requireAdmin(actor, group);

        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("A group name is required");
        }

        group.setName(trimToLength(name, 60));
        group.setDescription(trimToLength(description, 500));
        group.setOpenToNewMembers(openToNewMembers);

        return friendGroupRepository.save(group);
    }

    // Extended admin edit used by the group settings form. The smaller overload above
    // remains for callers that only update the original fields.
    @Transactional
    public FriendGroup updateGroup(User actor, Long groupId, String name, String description,
            GroupVibe vibe, GroupSizePreference size, MeetupStyle meetupStyle, Campus campus,
            Availability availability, TopInterest topInterest, boolean openToNewMembers) {
        if (vibe == null || size == null || meetupStyle == null || campus == null
                || availability == null || topInterest == null) {
            throw new IllegalArgumentException("Complete all group details");
        }

        FriendGroup group = requireGroup(groupId);
        requireAdmin(actor, group);

        if (groupMembershipRepository.countByGroup(group) > size.getMaxSize()) {
            throw new IllegalStateException("The selected group size is smaller than the current member count");
        }

        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("A group name is required");
        }

        group.setName(trimToLength(name, 60));
        group.setDescription(trimToLength(description, 500));
        group.setVibe(vibe);
        group.setSize_preference(size);
        group.setMaxMembers(size.getMaxSize());
        group.setMeetup_style(meetupStyle);
        group.setCampus(campus);
        group.setAvailability(availability);
        group.setTop_interest(topInterest);
        group.setOpenToNewMembers(openToNewMembers);

        return friendGroupRepository.save(group);
    }

    // Only a group admin can delete. Memberships go first so no rows are orphaned.
    @Transactional
    public void deleteGroup(User actor, Long groupId) {
        FriendGroup group = requireGroup(groupId);
        requireAdmin(actor, group);

        groupChatMessageRepository.deleteByGroup(group);
        groupMembershipRepository.deleteByGroup(group);
        friendGroupRepository.delete(group);
    }

    // ----- Membership -----

    @Transactional(readOnly = true)
    public List<GroupMembership> getMemberships(FriendGroup group) {
        if (group == null) {
            return new ArrayList<>();
        }
        return groupMembershipRepository.findByGroupOrderByJoinedAtAsc(group);
    }

    @Transactional(readOnly = true)
    public List<GroupMembership> getMyMemberships(User user) {
        if (user == null) {
            return new ArrayList<>();
        }
        return groupMembershipRepository.findByUserOrderByJoinedAtDesc(user);
    }

    @Transactional(readOnly = true)
    public GroupMembership getMembership(FriendGroup group, User user) {
        if (group == null || user == null) {
            return null;
        }
        return groupMembershipRepository.findByGroupAndUser(group, user).orElse(null);
    }

    @Transactional(readOnly = true)
    public boolean isMember(FriendGroup group, User user) {
        return getMembership(group, user) != null;
    }

    @Transactional(readOnly = true)
    public boolean isAdmin(FriendGroup group, User user) {
        if (isSitewideGroupAdmin(user)) {
            return true;
        }
        GroupMembership membership = getMembership(group, user);
        return membership != null && membership.getRole() == GroupRole.ADMIN;
    }

    @Transactional(readOnly = true)
    public long getMemberCount(FriendGroup group) {
        if (group == null) {
            return 0;
        }
        return groupMembershipRepository.countByGroup(group);
    }

    @Transactional
    public GroupMembership joinGroup(User user, Long groupId) {
        return addUserToOpenGroup(user, groupId, GroupRole.MEMBER);
    }

    // Requests made from the explore list wait for an existing admin's approval.
    @Transactional
    public GroupMembership requestToJoinGroup(User user, Long groupId) {
        return addUserToOpenGroup(user, groupId, GroupRole.PENDING);
    }

    private GroupMembership addUserToOpenGroup(User user, Long groupId, GroupRole role) {
        if (user == null) {
            throw new IllegalArgumentException("A user is required");
        }

        FriendGroup group = requireGroup(groupId);

        if (groupMembershipRepository.existsByGroupAndUser(group, user)) {
            throw new IllegalStateException("You are already a member of this group");
        }

        if (!group.isOpenToNewMembers()) {
            throw new IllegalStateException("This group is not accepting new members");
        }

        if (groupMembershipRepository.countByGroup(group) >= group.getMaxMembers()) {
            throw new IllegalStateException("This group is full");
        }

        return groupMembershipRepository.save(new GroupMembership(group, user, role));
    }

    // Leaving is always allowed. If the last admin leaves, the longest-standing remaining
    // member is promoted so the group is never left without an admin; if the last member
    // leaves, the group is deleted rather than left empty.
    @Transactional
    public void leaveGroup(User user, Long groupId) {
        FriendGroup group = requireGroup(groupId);

        GroupMembership membership = groupMembershipRepository.findByGroupAndUser(group, user)
                .orElseThrow(() -> new IllegalStateException("You are not a member of this group"));

        boolean wasAdmin = membership.getRole() == GroupRole.ADMIN;
        groupMembershipRepository.delete(membership);

        List<GroupMembership> remaining = groupMembershipRepository.findByGroupOrderByJoinedAtAsc(group);

        if (remaining.isEmpty()) {
            friendGroupRepository.delete(group);
            return;
        }

        if (wasAdmin && !hasAnyAdmin(remaining)) {
            GroupMembership successor = remaining.get(0);
            successor.setRole(GroupRole.ADMIN);
            groupMembershipRepository.save(successor);
        }
    }

    // Admin-only. Refuses to demote the last admin, which would strand the group.
    @Transactional
    public GroupMembership changeRole(User actor, Long groupId, long targetUserId, GroupRole newRole) {
        if (newRole == null) {
            throw new IllegalArgumentException("A role is required");
        }

        FriendGroup group = requireGroup(groupId);
        requireAdmin(actor, group);

        GroupMembership target = findMembershipByUserId(group, targetUserId);

        if (target.getRole() == newRole) {
            return target; // nothing to do
        }

        boolean isAllowedTransition =
                (target.getRole() == GroupRole.PENDING && newRole == GroupRole.MEMBER)
                || (target.getRole() == GroupRole.MEMBER && newRole == GroupRole.ADMIN)
                || (target.getRole() == GroupRole.ADMIN && newRole == GroupRole.MEMBER);
        if (!isAllowedTransition) {
            throw new IllegalStateException("That role change is not allowed");
        }

        if (newRole == GroupRole.MEMBER && isLastAdmin(group, target)) {
            throw new IllegalStateException("A group must keep at least one admin");
        }

        target.setRole(newRole);
        return groupMembershipRepository.save(target);
    }

    // Admin-only. An admin can't remove themselves here - they leave instead, which
    // runs the successor logic in leaveGroup.
    @Transactional
    public void removeMember(User actor, Long groupId, long targetUserId) {
        FriendGroup group = requireGroup(groupId);
        requireAdmin(actor, group);

        if (actor.getId() == targetUserId) {
            throw new IllegalStateException("Use 'Leave group' to remove yourself");
        }

        GroupMembership target = findMembershipByUserId(group, targetUserId);

        if (isLastAdmin(group, target)) {
            throw new IllegalStateException("A group must keep at least one admin");
        }

        groupMembershipRepository.delete(target);
    }

    // ----- Matching -----

    // Open groups the user isn't already in, scored and ordered best-first.
    @Transactional(readOnly = true)
    public List<GroupSuggestion> suggestGroupsFor(User user) {
        List<GroupSuggestion> suggestions = new ArrayList<>();

        GroupPreference preference = getPreference(user);
        if (preference == null) {
            return suggestions;
        }

        for (FriendGroup group : friendGroupRepository.findByOpenToNewMembersTrueOrderByCreatedAtDesc()) {
            if (groupMembershipRepository.existsByGroupAndUser(group, user)) {
                continue; // already in it
            }

            List<GroupMembership> memberships = groupMembershipRepository.findByGroupOrderByJoinedAtAsc(group);

            if (memberships.size() >= group.getMaxMembers()) {
                continue; // full
            }

            List<GroupPreference> memberPreferences = new ArrayList<>();
            for (GroupMembership membership : memberships) {
                GroupPreference memberPreference =
                        groupPreferenceRepository.findByUser(membership.getUser()).orElse(null);
                if (memberPreference != null) {
                    memberPreferences.add(memberPreference);
                }
            }

            int score = GroupMatchingAlgorithm.groupFit(preference, group, memberPreferences);
            suggestions.add(new GroupSuggestion(group, score, memberships.size()));
        }

        suggestions.sort(Comparator.comparingInt(GroupSuggestion::getScore).reversed());
        return suggestions;
    }

    // Builds a brand new group around this user out of everyone else who is looking and
    // not yet placed. Returns null when there aren't enough compatible students yet.
    @Transactional
    public FriendGroup autoMatchIntoGroup(User user) {
        GroupPreference preference = getPreference(user);

        if (preference == null || !preference.isComplete()) {
            throw new IllegalStateException("Complete the group finder questionnaire first");
        }

        if (!preference.isLookingForGroup()) {
            throw new IllegalStateException("Turn on 'looking for a group' before matching");
        }

        List<GroupPreference> pool = new ArrayList<>();

        for (GroupPreference candidate : groupPreferenceRepository.findByLookingForGroupTrue()) {
            if (candidate.getUser() == null || !candidate.isComplete()) {
                continue;
            }
            if (candidate.getUser().getId() == user.getId()) {
                continue; // the seed is added separately
            }
            // Only offer up students who aren't in a group yet, so the matcher spreads
            // people out instead of repeatedly grouping the same handful of users.
            if (!groupMembershipRepository.findByUserOrderByJoinedAtDesc(candidate.getUser()).isEmpty()) {
                continue;
            }
            pool.add(candidate);
        }

        GroupSizePreference size = preference.getSize_preference() == null
                ? GroupSizePreference.SMALL
                : preference.getSize_preference();

        List<GroupPreference> cluster = GroupMatchingAlgorithm.formGroupAround(
                preference, pool, size.getMinSize(), size.getMaxSize());

        if (cluster.isEmpty()) {
            return null; // not enough compatible students right now
        }

        FriendGroup group = new FriendGroup(
                GroupMatchingAlgorithm.suggestName(cluster),
                "Automatically matched by the group finder based on shared interests.",
                preference.getVibe(),
                preference.getMeetup_style(),
                preference.getCampus(),
                preference.getAvailability(),
                preference.getTop_interest(),
                size,
                user);
        group.setAutoGenerated(true);

        FriendGroup saved = friendGroupRepository.save(group);

        // The student who ran the matcher becomes the admin; everyone else joins as a member.
        groupMembershipRepository.save(new GroupMembership(saved, user, GroupRole.ADMIN));

        for (GroupPreference member : cluster) {
            if (member.getUser().getId() == user.getId()) {
                continue;
            }
            groupMembershipRepository.save(new GroupMembership(saved, member.getUser(), GroupRole.MEMBER));
        }

        return saved;
    }

    // ----- Helpers -----

    private FriendGroup requireGroup(Long groupId) {
        FriendGroup group = findGroup(groupId);

        if (group == null) {
            throw new IllegalArgumentException("Group not found");
        }

        return group;
    }

    private void requireAdmin(User actor, FriendGroup group) {
        if (actor == null) {
            throw new IllegalArgumentException("A user is required");
        }

        if (isSitewideGroupAdmin(actor)) {
            return;
        }

        Optional<GroupMembership> membership = groupMembershipRepository.findByGroupAndUser(group, actor);

        if (membership.isEmpty() || membership.get().getRole() != GroupRole.ADMIN) {
            throw new IllegalStateException("Only a group admin can do that");
        }
    }

    private boolean isSitewideGroupAdmin(User user) {
        return user != null && (user.getRole() == Role.ADMIN || user.getRole() == Role.MOD);
    }

    private GroupMembership findMembershipByUserId(FriendGroup group, long targetUserId) {
        for (GroupMembership membership : groupMembershipRepository.findByGroupOrderByJoinedAtAsc(group)) {
            if (membership.getUser().getId() == targetUserId) {
                return membership;
            }
        }

        throw new IllegalArgumentException("That user is not a member of this group");
    }

    private boolean isLastAdmin(FriendGroup group, GroupMembership membership) {
        if (membership.getRole() != GroupRole.ADMIN) {
            return false;
        }

        return groupMembershipRepository.countByGroupAndRole(group, GroupRole.ADMIN) <= 1;
    }

    private boolean hasAnyAdmin(List<GroupMembership> memberships) {
        for (GroupMembership membership : memberships) {
            if (membership.getRole() == GroupRole.ADMIN) {
                return true;
            }
        }
        return false;
    }

    private String trimToLength(String value, int maxLength) {
        if (value == null) {
            return null;
        }

        String trimmed = value.trim();

        if (trimmed.isEmpty()) {
            return null;
        }

        return trimmed.length() > maxLength ? trimmed.substring(0, maxLength) : trimmed;
    }

    // View model pairing a group with this viewer's fit score and its current headcount,
    // so templates can render the browse/suggestion list without extra queries.
    public static class GroupSuggestion {
        private final FriendGroup group;
        private final int score;
        private final int memberCount;

        public GroupSuggestion(FriendGroup group, int score, int memberCount) {
            this.group = group;
            this.score = score;
            this.memberCount = memberCount;
        }

        public FriendGroup getGroup() {
            return group;
        }

        public int getScore() {
            return score;
        }

        public int getMemberCount() {
            return memberCount;
        }
    }
}
