package com.cmpt276.group3.grouproject.models;

import java.time.LocalDateTime;

import com.cmpt276.group3.grouproject.enums.Availability;
import com.cmpt276.group3.grouproject.enums.Campus;
import com.cmpt276.group3.grouproject.enums.GroupSizePreference;
import com.cmpt276.group3.grouproject.enums.GroupVibe;
import com.cmpt276.group3.grouproject.enums.MeetupStyle;
import com.cmpt276.group3.grouproject.enums.TopInterest;

import jakarta.annotation.Nullable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Size;

// A friend group. Deliberately does NOT map its memberships as a collection - membership
// is always loaded through GroupMembershipRepository so nothing lazy-loads inside a template.
@Entity
@Table(name = "friend_groups")
public class FriendGroup {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Size(max = 60)
    @Column(nullable = false, length = 60)
    private String name;

    @Nullable
    @Size(max = 500)
    @Column(length = 500)
    private String description;

    // The group's own answers to the finder questions - a candidate is scored against these.
    @Nullable
    @Enumerated(EnumType.STRING)
    private GroupVibe vibe;

    @Nullable
    @Enumerated(EnumType.STRING)
    private MeetupStyle meetup_style;

    @Nullable
    @Enumerated(EnumType.STRING)
    private Campus campus;

    @Nullable
    @Enumerated(EnumType.STRING)
    private Availability availability;

    @Nullable
    @Enumerated(EnumType.STRING)
    private TopInterest top_interest;

    @Nullable
    @Enumerated(EnumType.STRING)
    private GroupSizePreference size_preference;

    // Hard ceiling on membership. Defaults from size_preference when the group is created.
    @Column(name = "max_members", nullable = false)
    private int maxMembers = 6;

    // When false the group is invite-only and stops showing up in the public browse list.
    @Column(name = "open_to_new_members", nullable = false)
    private boolean openToNewMembers = true;

    // True when the group was built by the auto-matcher rather than created by hand.
    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated = false;

    @Nullable
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "created_by_id")
    private User createdBy;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    public FriendGroup() {
    }

    public FriendGroup(String name, String description, GroupVibe vibe, MeetupStyle meetup_style,
            Campus campus, Availability availability, TopInterest top_interest,
            GroupSizePreference size_preference, User createdBy) {
        this.name = name;
        this.description = description;
        this.vibe = vibe;
        this.meetup_style = meetup_style;
        this.campus = campus;
        this.availability = availability;
        this.top_interest = top_interest;
        this.size_preference = size_preference;
        this.createdBy = createdBy;
        this.maxMembers = size_preference == null ? 6 : size_preference.getMaxSize();
        this.createdAt = LocalDateTime.now();
    }

    @PrePersist
    void setCreatedAt() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public GroupVibe getVibe() {
        return vibe;
    }

    public void setVibe(GroupVibe vibe) {
        this.vibe = vibe;
    }

    public MeetupStyle getMeetup_style() {
        return meetup_style;
    }

    public void setMeetup_style(MeetupStyle meetup_style) {
        this.meetup_style = meetup_style;
    }

    public Campus getCampus() {
        return campus;
    }

    public void setCampus(Campus campus) {
        this.campus = campus;
    }

    public Availability getAvailability() {
        return availability;
    }

    public void setAvailability(Availability availability) {
        this.availability = availability;
    }

    public TopInterest getTop_interest() {
        return top_interest;
    }

    public void setTop_interest(TopInterest top_interest) {
        this.top_interest = top_interest;
    }

    public GroupSizePreference getSize_preference() {
        return size_preference;
    }

    public void setSize_preference(GroupSizePreference size_preference) {
        this.size_preference = size_preference;
    }

    public int getMaxMembers() {
        return maxMembers;
    }

    public void setMaxMembers(int maxMembers) {
        this.maxMembers = maxMembers;
    }

    public boolean isOpenToNewMembers() {
        return openToNewMembers;
    }

    public void setOpenToNewMembers(boolean openToNewMembers) {
        this.openToNewMembers = openToNewMembers;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public User getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
